import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Alert,
  Share,
} from 'react-native';
import { FontAwesome5 as Icon } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useAuth } from '../contexts/AuthContext';
import { colors, shadows, typography } from '../theme/colors';

// Mock data for development
const MOCK_REPORT = {
  id: 'mock-report-1',
  userId: 'mock-user',
  month: '2025-11',
  generatedAt: new Date(),
  personalityType: 'Conscious Spender',
  summary: "You're doing great this month! You've shown impressive consistency with your grocery budget while treating yourself to some well-deserved tech upgrades. Your transport spending has improved significantly - that's progress worth celebrating!",
  strengths: [
    'Consistent with groceries - sticking to your weekly budget',
    'Excellent rent control - no surprises here',
    'Reduced transport costs by 15% from last month',
    'Smart meal planning helping save money',
    'Building a healthy emergency fund',
  ],
  improvements: [
    'Spontaneous with tech purchases - consider a monthly tech budget',
    'Restaurant spending spiked this month - maybe meal prep 2x per week?',
    'Entertainment subscriptions could be consolidated',
  ],
  recommendations: [
    'Set aside $50/month for tech purchases to avoid impulse buys',
    'Try cooking at home 2 extra times per week to save $60/month',
    'Consider a carpooling app to cut transport costs further',
    "You're saving 18% - aim for 20% next month!",
    'Review and cancel unused subscriptions to save $30/month',
  ],
  categoryInsights: [
    {
      category: 'Groceries',
      insight: 'Solid and consistent - you\'re a meal planning pro!',
      trend: 'stable'
    },
    {
      category: 'Tech',
      insight: 'A few splurges this month - maybe set a tech budget?',
      trend: 'up'
    },
    {
      category: 'Transport',
      insight: 'Great improvement from last month!',
      trend: 'down'
    },
    {
      category: 'Restaurants',
      insight: 'Higher than usual - try meal prepping!',
      trend: 'up'
    },
    {
      category: 'Utilities',
      insight: 'Consistent and well-managed!',
      trend: 'stable'
    },
  ],
  topCategories: [
    { category: 'Rent', amount: 1200, percentage: 40, frequency: 1 },
    { category: 'Groceries', amount: 450, percentage: 15, frequency: 12 },
    { category: 'Transport', amount: 300, percentage: 10, frequency: 8 },
    { category: 'Restaurants', amount: 280, percentage: 9.3, frequency: 14 },
    { category: 'Tech', amount: 250, percentage: 8.3, frequency: 3 },
  ],
  monthlyStats: {
    totalIncome: 4000,
    totalExpenses: 3000,
    netSavings: 1000,
    savingsRate: 25,
  },
};

const PersonalityReportScreen = ({ navigation }) => {
  const { user } = useAuth();
  const [report, setReport] = useState(MOCK_REPORT); // Using mock data
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);

  const handleGenerateReport = async () => {
    Alert.alert(
      'Generate Report',
      'This feature will generate a real AI personality report once Agent 1 (Firestore) is completed. For now, enjoy the mock data!',
      [{ text: 'OK' }]
    );
  };

  const handleShare = async () => {
    try {
      await Share.share({
        message: `My Expense Personality: ${report.personalityType}\n\n${report.summary}\n\nGenerated by Penny 💎`,
      });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  if (loading) {
    return (
      <View style={styles.centerContainer}>
        <ActivityIndicator size="large" color={colors.primary} />
      </View>
    );
  }

  if (!report) {
    return (
      <View style={styles.container}>
        <LinearGradient
          colors={colors.primaryGradient}
          style={styles.header}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 0 }}
        >
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Icon name="chevron-left" size={24} color={colors.text.primary} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Personality Report</Text>
          <View style={{ width: 24 }} />
        </LinearGradient>

        <View style={styles.emptyState}>
          <Icon name="chart-pie" size={80} color={colors.text.disabled} />
          <Text style={styles.emptyTitle}>No Report Yet</Text>
          <Text style={styles.emptyText}>
            Generate your first Expense Personality report to get personalized insights!
          </Text>
          <TouchableOpacity
            style={styles.generateButton}
            onPress={handleGenerateReport}
            disabled={generating}
          >
            {generating ? (
              <ActivityIndicator color={colors.text.primary} />
            ) : (
              <Text style={styles.generateButtonText}>Generate Report</Text>
            )}
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      {/* Header */}
      <LinearGradient
        colors={colors.primaryGradient}
        style={styles.header}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 0 }}
      >
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Icon name="chevron-left" size={24} color={colors.text.primary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>
          {new Date(report.month).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
        </Text>
        <TouchableOpacity onPress={() => navigation.navigate('ReportHistory')}>
          <Icon name="history" size={24} color={colors.text.primary} />
        </TouchableOpacity>
      </LinearGradient>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Personality Type Badge */}
        <View style={styles.personalityBadge}>
          <Icon name="star" size={40} color={colors.warning} />
          <Text style={styles.personalityType}>{report.personalityType}</Text>
          <Text style={styles.badgeSubtitle}>Your Spending Personality</Text>
        </View>

        {/* Summary */}
        <View style={styles.card}>
          <Text style={styles.summary}>{report.summary}</Text>
        </View>

        {/* Monthly Stats */}
        <View style={styles.statsCard}>
          <Text style={styles.sectionTitle}>Monthly Summary</Text>
          <View style={styles.statsRow}>
            <StatItem
              icon="arrow-down"
              label="Income"
              value={`$${report.monthlyStats.totalIncome.toFixed(0)}`}
              color={colors.income}
            />
            <StatItem
              icon="arrow-up"
              label="Expenses"
              value={`$${report.monthlyStats.totalExpenses.toFixed(0)}`}
              color={colors.expense}
            />
          </View>
          <View style={styles.statsRow}>
            <StatItem
              icon="piggy-bank"
              label="Saved"
              value={`$${report.monthlyStats.netSavings.toFixed(0)}`}
              color={colors.primary}
            />
            <StatItem
              icon="percent"
              label="Savings Rate"
              value={`${report.monthlyStats.savingsRate.toFixed(1)}%`}
              color={colors.income}
            />
          </View>
        </View>

        {/* Top Categories */}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Icon name="chart-bar" size={24} color={colors.primary} />
            <Text style={styles.sectionTitle}>Top Spending Categories</Text>
          </View>
          {report.topCategories.map((cat, index) => (
            <View key={index} style={styles.categoryCard}>
              <View style={styles.categoryRow}>
                <Text style={styles.categoryName}>{cat.category}</Text>
                <Text style={styles.categoryAmount}>${cat.amount.toFixed(0)}</Text>
              </View>
              <View style={styles.progressBarContainer}>
                <View style={[styles.progressBar, { width: `${cat.percentage}%` }]} />
              </View>
              <Text style={styles.categoryDetails}>
                {cat.percentage.toFixed(1)}% of total • {cat.frequency} transactions
              </Text>
            </View>
          ))}
        </View>

        {/* Strengths */}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Icon name="check-circle" size={24} color={colors.income} />
            <Text style={styles.sectionTitle}>Your Strengths</Text>
          </View>
          {report.strengths.map((strength, index) => (
            <View key={index} style={styles.listItem}>
              <Icon name="check" size={16} color={colors.income} />
              <Text style={styles.listItemText}>{strength}</Text>
            </View>
          ))}
        </View>

        {/* Improvements */}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Icon name="arrow-up" size={24} color={colors.warning} />
            <Text style={styles.sectionTitle}>Areas to Improve</Text>
          </View>
          {report.improvements.map((improvement, index) => (
            <View key={index} style={styles.listItem}>
              <Icon name="lightbulb" size={16} color={colors.warning} />
              <Text style={styles.listItemText}>{improvement}</Text>
            </View>
          ))}
        </View>

        {/* Recommendations */}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Icon name="magic" size={24} color={colors.primary} />
            <Text style={styles.sectionTitle}>AI Recommendations</Text>
          </View>
          {report.recommendations.map((rec, index) => (
            <View key={index} style={styles.listItem}>
              <Icon name="chevron-right" size={16} color={colors.primary} />
              <Text style={styles.listItemText}>{rec}</Text>
            </View>
          ))}
        </View>

        {/* Category Insights */}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Icon name="lightbulb" size={24} color={colors.warning} />
            <Text style={styles.sectionTitle}>Category Insights</Text>
          </View>
          {report.categoryInsights.map((insight, index) => (
            <View key={index} style={styles.categoryInsightCard}>
              <View style={styles.categoryInsightHeader}>
                <Text style={styles.categoryName}>{insight.category}</Text>
                <View style={styles.trendBadge}>
                  <Icon
                    name={insight.trend === 'up' ? 'arrow-up' : insight.trend === 'down' ? 'arrow-down' : 'minus'}
                    size={14}
                    color={insight.trend === 'up' ? colors.expense : insight.trend === 'down' ? colors.income : colors.text.tertiary}
                  />
                  <Text style={[
                    styles.trendText,
                    { color: insight.trend === 'up' ? colors.expense : insight.trend === 'down' ? colors.income : colors.text.tertiary }
                  ]}>
                    {insight.trend === 'up' ? 'Higher' : insight.trend === 'down' ? 'Lower' : 'Stable'}
                  </Text>
                </View>
              </View>
              <Text style={styles.categoryInsightText}>{insight.insight}</Text>
            </View>
          ))}
        </View>

        {/* Share Button */}
        <TouchableOpacity style={styles.shareButton} onPress={handleShare}>
          <Icon name="share-alt" size={20} color={colors.primary} />
          <Text style={styles.shareButtonText}>Share Report</Text>
        </TouchableOpacity>

        {/* Generate New Report Button */}
        <TouchableOpacity style={styles.generateNewButton} onPress={handleGenerateReport}>
          <Icon name="sync-alt" size={20} color={colors.text.primary} />
          <Text style={styles.generateNewButtonText}>Generate New Report</Text>
        </TouchableOpacity>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
};

const StatItem = ({ icon, label, value, color }) => (
  <View style={styles.statItem}>
    <Icon name={icon} size={20} color={color} />
    <Text style={styles.statLabel}>{label}</Text>
    <Text style={[styles.statValue, { color }]}>{value}</Text>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  headerTitle: {
    ...typography.h3,
    color: colors.text.primary,
  },
  content: {
    flex: 1,
  },
  personalityBadge: {
    alignItems: 'center',
    paddingVertical: 30,
    backgroundColor: colors.glass.background,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.glass.border,
  },
  personalityType: {
    ...typography.h1,
    marginTop: 15,
  },
  badgeSubtitle: {
    ...typography.caption,
    marginTop: 5,
  },
  card: {
    backgroundColor: colors.glass.background,
    padding: 20,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.glass.borderLight,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 10,
  },
  sectionTitle: {
    ...typography.h3,
  },
  summary: {
    ...typography.body,
    lineHeight: 24,
    color: colors.text.secondary,
  },
  statsCard: {
    backgroundColor: colors.glass.background,
    padding: 20,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.glass.borderLight,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    gap: 5,
  },
  statLabel: {
    ...typography.small,
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  categoryCard: {
    marginBottom: 15,
  },
  categoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  categoryName: {
    ...typography.body,
    fontWeight: '600',
  },
  categoryAmount: {
    ...typography.body,
    fontWeight: 'bold',
    color: colors.primary,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: colors.backgroundLight,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 5,
  },
  progressBar: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 4,
  },
  categoryDetails: {
    ...typography.small,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
    gap: 10,
  },
  listItemText: {
    flex: 1,
    ...typography.body,
    lineHeight: 22,
    color: colors.text.secondary,
  },
  categoryInsightCard: {
    backgroundColor: colors.backgroundLight,
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
  },
  categoryInsightHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  trendBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.glass.background,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.glass.border,
  },
  trendText: {
    fontSize: 12,
    fontWeight: '600',
  },
  categoryInsightText: {
    ...typography.caption,
    lineHeight: 20,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 15,
    marginHorizontal: 20,
    marginTop: 10,
    backgroundColor: colors.glass.background,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.primary,
    ...shadows.md,
  },
  shareButtonText: {
    ...typography.body,
    fontWeight: '600',
    color: colors.primary,
  },
  generateNewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 15,
    marginHorizontal: 20,
    marginTop: 10,
    backgroundColor: colors.primary,
    borderRadius: 25,
    ...shadows.md,
  },
  generateNewButtonText: {
    ...typography.body,
    fontWeight: '600',
    color: colors.text.primary,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyTitle: {
    ...typography.h2,
    marginTop: 20,
  },
  emptyText: {
    ...typography.bodySecondary,
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 30,
  },
  generateButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 40,
    paddingVertical: 15,
    borderRadius: 25,
    minWidth: 200,
    alignItems: 'center',
    ...shadows.md,
  },
  generateButtonText: {
    color: colors.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
});

export default PersonalityReportScreen;
